/**
 * Structured CPU name parts — each segment of the product name broken out.
 * Generated from data.ts names. Do not hand-edit; regenerate with _gen-names.mjs.
 */

export type CpuNameParts = {
  corporateBrand: string;  // "Intel" | "AMD" | "Apple"
  productBrand: string;    // "Core" | "Ryzen" | "Processor" | "M3"
  modifier: string;        // "Ultra" | "Threadripper" | ""
  tier: string;            // "i9" | "i7" | "i5" | "i3" | "9" | "7" | "5" | "3" | ""
  qualifier: string;       // "Pro" | ""
  prefix: string;          // "N" | "" (model number prefix, e.g. N-series)
  model: string;           // "14900" | "9950" | "150" | ""
  suffix: string;          // "K" | "KF" | "KS" | "F" | "X" | "X3D" | "XT" | "G" | "T" | ""
  variant: string;         // "Plus" | ""
};

/** Lookup: full CPU name → structured parts */
export const cpuNames: Record<string, CpuNameParts> = {
  "Intel Core Ultra 7 270K Plus": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "7", qualifier: "", prefix: "", model: "270", suffix: "K", variant: "Plus" },
  "AMD Ryzen 9 9950X3D2": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "9950", suffix: "X3D2", variant: "" },
  "Apple M3 Ultra": { corporateBrand: "Apple", productBrand: "M3", modifier: "Ultra", tier: "", qualifier: "", prefix: "", model: "", suffix: "", variant: "" },
  "AMD Ryzen 9 9950X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "9950", suffix: "X3D", variant: "" },
  "AMD Ryzen 9 9950X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "9950", suffix: "X", variant: "" },
  "Intel Core i9 14900KS": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "14900", suffix: "KS", variant: "" },
  "Intel Core Ultra 9 285K": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "9", qualifier: "", prefix: "", model: "285", suffix: "K", variant: "" },
  "AMD Ryzen 9 9900X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "9900", suffix: "X3D", variant: "" },
  "Intel Core Ultra 7 265KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "7", qualifier: "", prefix: "", model: "265", suffix: "KF", variant: "" },
  "Intel Core i9 14900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "14900", suffix: "K", variant: "" },
  "Intel Core i9 13900KS": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "13900", suffix: "KS", variant: "" },
  "Intel Core Ultra 7 265K": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "7", qualifier: "", prefix: "", model: "265", suffix: "K", variant: "" },
  "AMD Ryzen 9 9900X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "9900", suffix: "X", variant: "" },
  "Intel Core i9 14900KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "14900", suffix: "KF", variant: "" },
  "AMD Ryzen 9 7950X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "7950", suffix: "X", variant: "" },
  "Intel Core Ultra 5 250K Plus": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "250", suffix: "K", variant: "Plus" },
  "Intel Core i9 13900KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "13900", suffix: "KF", variant: "" },
  "Intel Core i9 13900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "13900", suffix: "K", variant: "" },
  "AMD Ryzen 9 7950X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "7950", suffix: "X3D", variant: "" },
  "AMD Ryzen 7 9850X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "9850", suffix: "X3D", variant: "" },
  "Intel Core i7 14700KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "14700", suffix: "KF", variant: "" },
  "Intel Core i7 14700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "14700", suffix: "K", variant: "" },
  "Intel Core Ultra 7 265F": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "7", qualifier: "", prefix: "", model: "265", suffix: "F", variant: "" },
  "AMD Ryzen 7 9800X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "9800", suffix: "X3D", variant: "" },
  "Intel Core i9 14900F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "14900", suffix: "F", variant: "" },
  "Intel Core Ultra 9 285": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "9", qualifier: "", prefix: "", model: "285", suffix: "", variant: "" },
  "Intel Core i9 14900": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "14900", suffix: "", variant: "" },
  "Intel Core Ultra 7 265": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "7", qualifier: "", prefix: "", model: "265", suffix: "", variant: "" },
  "Intel Core Ultra 5 245K": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "245", suffix: "K", variant: "" },
  "AMD Ryzen 7 9700X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "9700", suffix: "X", variant: "" },
  "AMD Ryzen 9 7900X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "7900", suffix: "X3D", variant: "" },
  "Intel Core i9 13900": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "13900", suffix: "", variant: "" },
  "Intel Core Ultra 5 245KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "245", suffix: "KF", variant: "" },
  "Intel Core i9 13900F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "13900", suffix: "F", variant: "" },
  "AMD Ryzen 9 7900": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "7900", suffix: "", variant: "" },
  "AMD Ryzen 9 7900X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "7900", suffix: "X", variant: "" },
  "Intel Core i7 13700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "13700", suffix: "K", variant: "" },
  "AMD Ryzen 9 Pro 9945": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "Pro", prefix: "", model: "9945", suffix: "", variant: "" },
  "AMD Ryzen 7 9700F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "9700", suffix: "F", variant: "" },
  "Intel Core i7 14700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "14700", suffix: "", variant: "" },
  "Intel Core i7 13700KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "13700", suffix: "KF", variant: "" },
  "Intel Core Ultra 5 235": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "235", suffix: "", variant: "" },
  "Intel Core i7 14700F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "14700", suffix: "F", variant: "" },
  "AMD Ryzen 7 Pro 9745": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "Pro", prefix: "", model: "9745", suffix: "", variant: "" },
  "AMD Ryzen 5 Pro 9645": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "Pro", prefix: "", model: "9645", suffix: "", variant: "" },
  "AMD Ryzen 5 9600X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "9600", suffix: "X", variant: "" },
  "Intel Core i5 14600KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14600", suffix: "KF", variant: "" },
  "Intel Core i9 12900KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "12900", suffix: "KF", variant: "" },
  "Intel Core i5 14600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14600", suffix: "K", variant: "" },
  "AMD Ryzen 7 7700X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "7700", suffix: "X", variant: "" },
  "Intel Core i5 13600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "13600", suffix: "K", variant: "" },
  "Intel Core i9 12900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "12900", suffix: "K", variant: "" },
  "AMD Ryzen 5 9500F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "9500", suffix: "F", variant: "" },
  "Intel Core i7 13700F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "13700", suffix: "F", variant: "" },
  "AMD Ryzen 7 7700": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "7700", suffix: "", variant: "" },
  "AMD Ryzen 7 7800X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "7800", suffix: "X", variant: "" },
  "Intel Core i5 13600KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "13600", suffix: "KF", variant: "" },
  "Intel Core i7 13700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "13700", suffix: "", variant: "" },
  "Intel Core Ultra 5 225F": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "225", suffix: "F", variant: "" },
  "Intel Core i7 12700KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "12700", suffix: "KF", variant: "" },
  "AMD Ryzen Threadripper 3990X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "Threadripper", tier: "", qualifier: "", prefix: "", model: "3990", suffix: "X", variant: "" },
  "AMD Ryzen Threadripper 3970X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "Threadripper", tier: "", qualifier: "", prefix: "", model: "3970", suffix: "X", variant: "" },
  "Intel Core i5 14600": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14600", suffix: "", variant: "" },
  "Intel Core Ultra 5 225": { corporateBrand: "Intel", productBrand: "Core", modifier: "Ultra", tier: "5", qualifier: "", prefix: "", model: "225", suffix: "", variant: "" },
  "Intel Core i7 12700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "12700", suffix: "K", variant: "" },
  "Intel Core i5 14500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14500", suffix: "", variant: "" },
  "AMD Ryzen 7 7800X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "7800", suffix: "X3D", variant: "" },
  "AMD Ryzen 5 7600X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "7600", suffix: "X", variant: "" },
  "AMD Ryzen 9 5950X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "5950", suffix: "X", variant: "" },
  "AMD Ryzen 7 8700F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "8700", suffix: "F", variant: "" },
  "AMD Ryzen 7 8700G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "8700", suffix: "G", variant: "" },
  "Intel Core i5 13600": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "13600", suffix: "", variant: "" },
  "AMD Ryzen 5 7500F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "7500", suffix: "F", variant: "" },
  "Intel Core i7 12700F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "12700", suffix: "F", variant: "" },
  "AMD Ryzen 5 8600G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "8600", suffix: "G", variant: "" },
  "AMD Ryzen 5 7600": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "7600", suffix: "", variant: "" },
  "Intel Core i7 12700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "12700", suffix: "", variant: "" },
  "AMD Ryzen Threadripper 3960X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "Threadripper", tier: "", qualifier: "", prefix: "", model: "3960", suffix: "X", variant: "" },
  "Intel Core i5 12600KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12600", suffix: "KF", variant: "" },
  "AMD Ryzen 9 5900X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "5900", suffix: "X", variant: "" },
  "AMD Ryzen 5 7400F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "7400", suffix: "F", variant: "" },
  "AMD Ryzen 5 7600X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "7600", suffix: "X3D", variant: "" },
  "Intel Core i5 12600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12600", suffix: "K", variant: "" },
  "AMD Ryzen 5 8400F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "8400", suffix: "F", variant: "" },
  "AMD Ryzen 5 8500G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "8500", suffix: "G", variant: "" },
  "Intel Core i5 14400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14400", suffix: "F", variant: "" },
  "AMD Ryzen 9 5900": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "5900", suffix: "", variant: "" },
  "Intel Core i5 14400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "14400", suffix: "", variant: "" },
  "Intel Core i5 12600": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12600", suffix: "", variant: "" },
  "Intel Core i5 13400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "13400", suffix: "F", variant: "" },
  "Intel Core i9 11900KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "11900", suffix: "KF", variant: "" },
  "Intel Core i9 11900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "11900", suffix: "K", variant: "" },
  "Intel Core i5 13400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "13400", suffix: "", variant: "" },
  "Intel Core i5 12500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12500", suffix: "", variant: "" },
  "AMD Ryzen 7 5800X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5800", suffix: "X", variant: "" },
  "AMD Ryzen 9 3950X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "3950", suffix: "X", variant: "" },
  "AMD Ryzen 7 5800X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5800", suffix: "X3D", variant: "" },
  "AMD Ryzen 7 5700X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5700", suffix: "X", variant: "" },
  "Intel Core i7 11700KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "11700", suffix: "KF", variant: "" },
  "Intel Core i3 14100": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "14100", suffix: "", variant: "" },
  "Intel Core i7 11700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "11700", suffix: "K", variant: "" },
  "Intel Core i3 14100F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "14100", suffix: "F", variant: "" },
  "AMD Ryzen 7 5700G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5700", suffix: "G", variant: "" },
  "Intel Core i3 12100F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "12100", suffix: "F", variant: "" },
  "Intel Core i5 12400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12400", suffix: "F", variant: "" },
  "Intel Core i5 12400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "12400", suffix: "", variant: "" },
  "AMD Ryzen 7 5800": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5800", suffix: "", variant: "" },
  "Intel Core i9 11900": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "11900", suffix: "", variant: "" },
  "AMD Ryzen 7 5700X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "5700", suffix: "X3D", variant: "" },
  "AMD Ryzen 3 8300G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "8300", suffix: "G", variant: "" },
  "Intel Core i3 13100F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "13100", suffix: "F", variant: "" },
  "Intel Core i7 11700F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "11700", suffix: "F", variant: "" },
  "Intel Core i5 11600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "11600", suffix: "K", variant: "" },
  "Intel Core i7 11700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "11700", suffix: "", variant: "" },
  "AMD Ryzen 5 5600X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5600", suffix: "X", variant: "" },
  "AMD Ryzen 9 3900XT": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "3900", suffix: "XT", variant: "" },
  "AMD Ryzen 9 3900X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "9", qualifier: "", prefix: "", model: "3900", suffix: "X", variant: "" },
  "Intel Core i3 13100": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "13100", suffix: "", variant: "" },
  "AMD Ryzen 5 5600": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5600", suffix: "", variant: "" },
  "Intel Core i9 10850K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "10850", suffix: "K", variant: "" },
  "AMD Ryzen 5 5600F": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5600", suffix: "F", variant: "" },
  "AMD Ryzen 5 5600X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5600", suffix: "X3D", variant: "" },
  "Intel Core i5 11600KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "11600", suffix: "KF", variant: "" },
  "AMD Ryzen 5 5500X3D": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5500", suffix: "X3D", variant: "" },
  "AMD Ryzen 5 5500": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5500", suffix: "", variant: "" },
  "AMD Ryzen 5 5600G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "5600", suffix: "G", variant: "" },
  "Intel Core i3 12100": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "12100", suffix: "", variant: "" },
  "Intel Core i5 11400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "11400", suffix: "F", variant: "" },
  "Intel Core i5 11400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "11400", suffix: "", variant: "" },
  "AMD Ryzen 7 3800XT": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "3800", suffix: "XT", variant: "" },
  "Intel Core i9 10900KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "10900", suffix: "KF", variant: "" },
  "AMD Ryzen 7 3800X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "3800", suffix: "X", variant: "" },
  "Intel Core i9 10900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "10900", suffix: "K", variant: "" },
  "Intel Core i7 10700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "10700", suffix: "K", variant: "" },
  "Intel Core i9 10900": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "10900", suffix: "", variant: "" },
  "Intel Core i7 10700KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "10700", suffix: "KF", variant: "" },
  "AMD Ryzen 5 3600X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "3600", suffix: "X", variant: "" },
  "AMD Ryzen 7 3700X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "3700", suffix: "X", variant: "" },
  "AMD Ryzen 5 3600XT": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "3600", suffix: "XT", variant: "" },
  "Intel Core i7 9700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "9700", suffix: "K", variant: "" },
  "Intel Core i9 9900K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i9", qualifier: "", prefix: "", model: "9900", suffix: "K", variant: "" },
  "Intel Core i5 10600KF": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10600", suffix: "KF", variant: "" },
  "Intel Core i7 10700F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "10700", suffix: "F", variant: "" },
  "AMD Ryzen 3 5300G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "5300", suffix: "G", variant: "" },
  "AMD Ryzen 5 Pro 4650G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "Pro", prefix: "", model: "4650", suffix: "G", variant: "" },
  "Intel Core i7 10700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "10700", suffix: "", variant: "" },
  "Intel Core i5 10600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10600", suffix: "K", variant: "" },
  "AMD Ryzen 5 3600": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "3600", suffix: "", variant: "" },
  "AMD Ryzen 5 4500": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "4500", suffix: "", variant: "" },
  "AMD Ryzen 5 4600G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "4600", suffix: "G", variant: "" },
  "Intel Core i7 8700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "8700", suffix: "K", variant: "" },
  "AMD Ryzen 3 4300G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "4300", suffix: "G", variant: "" },
  "Intel Core i5 9600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "9600", suffix: "K", variant: "" },
  "Intel Core i7 9700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "9700", suffix: "", variant: "" },
  "Intel Core i5 10500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10500", suffix: "", variant: "" },
  "Intel Core i7 7700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "7700", suffix: "", variant: "" },
  "AMD Ryzen 3 4100": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "4100", suffix: "", variant: "" },
  "Intel Core i5 10400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10400", suffix: "F", variant: "" },
  "Intel Core i7 8700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "8700", suffix: "", variant: "" },
  "Intel Core i5 8600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "8600", suffix: "K", variant: "" },
  "AMD Ryzen 7 2700X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "2700", suffix: "X", variant: "" },
  "Intel Core i3 10105F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "10105", suffix: "F", variant: "" },
  "Intel Core i3 10100F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "10100", suffix: "F", variant: "" },
  "AMD Ryzen 3 3100": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "3100", suffix: "", variant: "" },
  "Intel Core i5 10400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10400", suffix: "", variant: "" },
  "Intel Core i7 7700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "7700", suffix: "K", variant: "" },
  "AMD Ryzen 5 2600X": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "2600", suffix: "X", variant: "" },
  "AMD Ryzen 7 2700": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "7", qualifier: "", prefix: "", model: "2700", suffix: "", variant: "" },
  "Intel Core i3 10100": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "10100", suffix: "", variant: "" },
  "Intel Core i5 9500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "9500", suffix: "", variant: "" },
  "Intel Core i5 9400F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "9400", suffix: "F", variant: "" },
  "Intel Core i5 8500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "8500", suffix: "", variant: "" },
  "AMD Ryzen 5 2600": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "2600", suffix: "", variant: "" },
  "Intel Core i7 6700K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "6700", suffix: "K", variant: "" },
  "Intel Core i5 10500T": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "10500", suffix: "T", variant: "" },
  "Intel Core i3 9100F": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "9100", suffix: "F", variant: "" },
  "Intel Core i5 8400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "8400", suffix: "", variant: "" },
  "Intel Core i5 6600K": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "6600", suffix: "K", variant: "" },
  "AMD Ryzen 5 3400G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "3400", suffix: "G", variant: "" },
  "AMD Ryzen 5 1600": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "1600", suffix: "", variant: "" },
  "Intel Core i7 6700": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i7", qualifier: "", prefix: "", model: "6700", suffix: "", variant: "" },
  "AMD Ryzen 3 3200G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "3200", suffix: "G", variant: "" },
  "AMD Ryzen 5 2400G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "5", qualifier: "", prefix: "", model: "2400", suffix: "G", variant: "" },
  "Intel Core i5 7500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "7500", suffix: "", variant: "" },
  "Intel Processor N150": { corporateBrand: "Intel", productBrand: "Processor", modifier: "", tier: "", qualifier: "", prefix: "N", model: "150", suffix: "", variant: "" },
  "AMD Ryzen 3 2200G": { corporateBrand: "AMD", productBrand: "Ryzen", modifier: "", tier: "3", qualifier: "", prefix: "", model: "2200", suffix: "G", variant: "" },
  "Intel Core i5 6500": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "6500", suffix: "", variant: "" },
  "Intel Core i3 8100": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i3", qualifier: "", prefix: "", model: "8100", suffix: "", variant: "" },
  "Intel Processor N250": { corporateBrand: "Intel", productBrand: "Processor", modifier: "", tier: "", qualifier: "", prefix: "N", model: "250", suffix: "", variant: "" },
  "Intel Core i5 7400": { corporateBrand: "Intel", productBrand: "Core", modifier: "", tier: "i5", qualifier: "", prefix: "", model: "7400", suffix: "", variant: "" },
};
