import { H2, H3, Paragraph, Bold, InlineCode } from "@/components/typography";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export default function TsxPipelineHelloWorld() {
  return (
    <>
      <Paragraph>
        This is the first piece of <Bold>TSX-as-content</Bold> on the site. The
        title, description, and date above this paragraph come from the
        database — this file only renders the body.
      </Paragraph>

      <H2>Why this matters</H2>
      <Paragraph>
        Markdown is the public standard. TSX content is the private power. Same
        URL pattern (<InlineCode>/posts/[slug]</InlineCode>), same header
        chrome, but the body can be any React component you want.
      </Paragraph>

      <Card>
        <CardHeader>
          <CardTitle>Proof of life</CardTitle>
        </CardHeader>
        <CardContent>
          <Paragraph>
            If you can see this card with shadcn styling, the dynamic import
            wired up correctly and Server Component rendering works inside the
            existing route shell.
          </Paragraph>
        </CardContent>
      </Card>

      <H3>What gets stored in the DB</H3>
      <Paragraph>
        Slug, title, description, tags, type — generated by Claude from this
        file&apos;s source. The <InlineCode>format</InlineCode> column says{" "}
        <InlineCode>tsx</InlineCode>, so the route knows to dynamic-import
        instead of reading markdown.
      </Paragraph>
    </>
  );
}
