"use client";

import { BotIcon, PenLineIcon } from "lucide-react";
import { Tooltip as TooltipPrimitive } from "radix-ui";

import type { ContentRow } from "@/modules/content/queries";
import styles from "./content-header.module.css";

const KIND_LABELS: Record<ContentRow["type"], string> = {
  post: "Post",
  doc: "Doc",
  thought: "Thought",
  design: "Design",
  link: "Link",
};

/**
 * NULL authorship means "whatever this type usually is", not "unknown".
 * Posts are my writing; thoughts and designs are artifacts of agent work,
 * prose and interactive respectively. An explicit value on the row always
 * wins, and handwritten has nothing to disclose.
 */
const GENERATED_BY_DEFAULT: ContentRow["type"][] = ["thought", "design"];
const HANDWRITTEN_BY_DEFAULT: ContentRow["type"][] = ["post"];

const ASSISTED_NOTE =
  "Written by me, with a coding agent helping on structure and edits.";

const GENERATED_NOTES: Partial<Record<ContentRow["type"], string>> = {
  thought:
    "An AI-generated artifact of work I did with a coding agent. Reference material, not finished writing.",
  design:
    "An AI-generated design experiment, vibecoded quickly. Not a finished or reviewed design.",
};

const GENERATED_FALLBACK =
  "Generated by a coding agent and reviewed by me before publishing.";

function authorshipFor(row: ContentRow) {
  const handwritten =
    row.authorship === "handwritten" ||
    (row.authorship === null && HANDWRITTEN_BY_DEFAULT.includes(row.type));

  if (handwritten) {
    return { icon: PenLineIcon, label: "Written by hand", note: null };
  }

  const generated =
    row.authorship === "ai-generated" ||
    (row.authorship === null && GENERATED_BY_DEFAULT.includes(row.type));

  if (generated) {
    return {
      icon: BotIcon,
      label: "AI-generated",
      note:
        row.authorship_note ??
        GENERATED_NOTES[row.type] ??
        GENERATED_FALLBACK,
    };
  }

  return {
    icon: BotIcon,
    label: "AI-assisted",
    note: row.authorship_note ?? ASSISTED_NOTE,
  };
}

/** Quiet surface in the page's own colours — no arrow, no help cursor. */
function DisclosureTooltip({
  note,
  children,
}: {
  note: string;
  children: React.ReactNode;
}) {
  return (
    <TooltipPrimitive.Root>
      <TooltipPrimitive.Trigger asChild>{children}</TooltipPrimitive.Trigger>
      <TooltipPrimitive.Portal>
        <TooltipPrimitive.Content
          side="bottom"
          align="start"
          sideOffset={6}
          className={styles.tooltip}
        >
          {note}
        </TooltipPrimitive.Content>
      </TooltipPrimitive.Portal>
    </TooltipPrimitive.Root>
  );
}

function formatDate(value: string) {
  return new Date(value).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/**
 * One header for every content type. Provenance sits on the meta line beside
 * the date rather than in a callout above the title, with the full disclosure
 * behind a tooltip for readers who want it.
 */
export function ContentHeader({ row }: { row: ContentRow }) {
  const { icon: AuthorshipIcon, label, note } = authorshipFor(row);

  const mark = (
    <span className={styles.authorship}>
      <AuthorshipIcon className={styles.authorshipIcon} aria-hidden="true" />
      {label}
    </span>
  );

  return (
    <header className={styles.header}>
      <span className={styles.kind}>{KIND_LABELS[row.type]}</span>

      <h1 className={styles.title}>{row.title}</h1>

      {row.description && (
        <p className={styles.description}>{row.description}</p>
      )}

      <div className={styles.meta}>
        <span>{formatDate(row.created_at)}</span>
        <span aria-hidden="true">·</span>
        {note ? (
          <DisclosureTooltip note={note}>
            <button type="button" className={styles.disclosureTrigger}>
              {mark}
            </button>
          </DisclosureTooltip>
        ) : (
          mark
        )}
      </div>

      <div className={styles.rule} />
    </header>
  );
}
